### PR TITLE
Make Cobblestone / Stone Generators not generate Ores anymore (also add more blocks!)

### LINKED ISSUE #238: Cobble Gen Randomizer causes ores to generate from cobblegens
### Describe your suggestion

https://www.curseforge.com/minecraft/mc-mods/cobblegenrandomizer

As shipped it doesn't even drop the new vanilla MC copper ore, let alone any of the modded ores that would be nice.

### Why would you like this added/changed?

Generate all vanilla ores and most of the modded ones.

Dirt as the 'catalyst' block as the underside of the reaction has been added as a fallback for anyone that depends on the prior behavior.  I'd prefer to use soul_dirt for the nether, but that's vanilla behavior.

Notably:
* Skipped the Occultism specific ores; to retain a reason to use Occultism's miners if someone's in that mod as well as progression gating.
* Didn't include Thermal's Niter or Sulfur ores, I never use them and the small sample size I talked to haven't used them either.  They could be added for completeness.

The drop weight is just an initial guess, tuning / tweaking suggested.

``` TOML
# config/cobblegenrandomizer-common.toml
[general]
	use_config = true
	[general.lists]
		#Cobble gen
		block_list_cobble = [
			"minecraft:cobblestone|60",
			"minecraft:coal_ore|25",
			"minecraft:iron_ore|20",
			"minecraft:redstone_ore|20",
			"minecraft:lapis_ore|20",
			"minecraft:emerald_ore|5",
			"minecraft:gold_ore|10",
			"minecraft:diamond_ore|5",
			"minecraft:copper_ore|20",
			"create:zinc_ore|5",
			"ftbic:alluminum_ore|5",
			"ftbic:lead_ore|5",
			"ftbic:tin_ore|5",
			"thermal:silver_ore|5",
			"thermal:nickle_ore|2",
			"ae2:quartz_ore|2",
			"thermal:cinnabar_ore|1",
			"ftbic:uranium_ore|1",
			"ftbic:iridium_ore|1",
			"mekanism:osmium_ore|5"]
		#Stone gen == $stones +++ FIXME: Stone weights
		block_list_stone = [
			"minecraft:stone|30",
			"minecraft:granite|10",
			"minecraft:diorite|10",
			"minecraft:andesite|10",
			"minecraft:deepslate|30",
			"minecraft:calcite|5",
			"minecraft:tuft|5",
			"minecraft:dripstone|5",
			"create:asurine|1",
			"create:crimsite|1",
			"create:limestone|1",
			"create:ochrum|1",
			"create:scoria|1",
			"create:scorchia|1",
			"create:veridium|1",
			"quark:limestone|1",
			"quark:jasper|1",
			"quark:shale|1",
			"quark:myalite|1",
			"quark:dusky_myalite|1",
			"quark:permafrost|1",
			"byg:red_rock|1",
			"byg:rocky_stone|1",
			"byg:travertine|1",
			"byg:scoria_stone|1",
			"byg:soapstone|1",
			"minecraft:sand|1",
			"minecraft:red_sand|1",
			"byg:black_sand|1",
			"byg:blue_sand|1",
			"byg:purple_sand|1",
			"byg:windswept_sandstone|1",
			"byg:white_sand|1",
			"byg:ether_stone|1",
			"byg:purpur_stone|1"]
		#Basalt gen
		block_list_basalt = [
			"minecraft:basalt|60",
			"minecraft:blackstone|60",
			"minecraft:netherrack|60",
			"minecraft:nether_quartz_ore|30",
			"minecraft:nether_gold_ore|30",
			"minecraft:ancient_debris|1",
			"rftoolsbase:dimensionalshard_nether|1",
			"tconstruct:cobalt_core|1"]

		#Custom settings
		[general.lists.custom]
			# End stone generators?
			# Dirt under the generation area == Old vanilla (no copper) mod behavior
			custom_generators = [
				["cobblestone", "minecraft:end_stone", ["minecraft:end_stone|1"]],
				["stone", "minecraft:end_stone", ["minecraft:end_stone|1"]],
				["cobblestone", "minecraft:dirt", [
					"minecraft:cobblestone|60",
					"minecraft:coal_ore|25",
					"minecraft:iron_ore|20",
					"minecraft:redstone_ore|20",
					"minecraft:lapis_ore|20",
					"minecraft:emerald_ore|5",
					"minecraft:gold_ore|10",
					"minecraft:diamond_ore|5"]],
				["stone", "minecraft:dirt", [
					"minecraft:stone|30",
					"minecraft:granite|10",
					"minecraft:diorite|10",
					"minecraft:andesite|10"]],
				["basalt", "minecraft:dirt", [
					"minecraft:basalt|60",
					"minecraft:blackstone|60",
					"minecraft:netherrack|60",
					"minecraft:nether_quartz_ore|30",
					"minecraft:nether_gold_ore|30",
					"minecraft:ancient_debris|1"]]
			]
```

### PR DESCRIPTION
**Pull request by Kanzaji**
Resolving errors from a try of fix #238

### CODE REVIEW

**Comment by Kanzaji** [comment]
Okay so as I can see, Thermal and IF cobblegens seems to add a lot of the stuff in on their own ^^" So I think fix for the errors is enough from me here. Literally half of the list is already added *on default*, so just a list of stuff that is in the modpack should be enough :P Still not I am working on Cobblegens ^^" So

**Comment by Kanzaji** [comment]
Okay I did lie, did some testing and it looks like the js scripts work only for Thermal and IF gens, and "vanilla type" one is defined in different way, so here all duplicates have been removed :D

**Comment by Kanzaji** [comment]
Okay so config for Vanilla Type gen was changed a lot by mod itself. It did delete (probably) all non-existent blocks from it, and one was missing so I added it back :D
Don't be scared of a lot missing 😅 I added only `, ["stone", "byg:brimstone", ["byg:brimstone"]` one!

**Comment by NielsPilgaard** [comment]
Oh, I committed before I was done 😅 thanks for fixing it! 

However, did the quark / create etc stones that we have in the pack, that were in the list cause issues? Cause there's more to it than just adding IF / Thermal compat, there's also tooltips and adding them to tags.

**Comment by Kanzaji** [comment]
🤔 I am now adding missing ones to the list, but those that I've deleted are 99% gone ^^" Will double check anyway!
JEI tooltips list was also updated to the "non-error" list, but with tags there could be a problem...
if tags use the same list as Thermal/IF gens, then those in the comment will not have added tags. I do have an idea for fixing this however:
I will create another list of those specifically for tag addition, and change tag scrip to use that one!

**Comment by Kanzaji** [comment]
Okay now just tags :P

**Comment by Kanzaji** [comment]
Okay everything should be fine ^^"
I did found other idea to fix tags, so I just added exclude list of stones/cobbles that are duplicated, and added a bit of a code that will ignore them while adding custom ones to IF / Thermal / Pedestals stuff (even tho its not implemented)

**Comment by Kanzaji** [comment]
Oh and also about those stones that were in the list and causing issues:
Those that were deleted are not present in the game, and duplicates were commented ^^" So it should be fine :D Not present ones were causing KubeJS errors, so they needed to be deleted.

**Comment by Kanzaji** [comment]
Also changed a name of PR for better looking in changelog 😉

**Review by NielsPilgaard — APPROVED** [review]
Seems like a few of the newer Create stones are missing from the CobblegenRandomizer config, but it looks like you've covered everything else :D

I can either merge as is, or would you like to add the Create stones?

**Comment by Kanzaji** [comment]
I am coming back home from vacation atm :sweat_smile: so if you don't want to wait 4-5 hours for a fix you can merge it :D

**Comment by NielsPilgaard** [comment]
I shall wait anyway! 😄

**Comment by Kanzaji** [comment]
Fixed :D

**Comment by NielsPilgaard** [comment]
A few of the #cobbleworks stones and cobblestones don't have custom generator recipes in the cobblegenrandomizer config still, could you perhaps have a look again? :x

**Comment by Kanzaji** [comment]
Sure thing 😄

**Comment by NielsPilgaard** [comment]
Thanks \○/

**Pull request merged**
