### PR TITLE
Fix typo and quest in Occultism chapter

### LINKED ISSUE #295: [bug] Quest Book - Occultism - Janitor / Cleaner won't unlock
### Modpack Version

2.3.0

### Describe your issue.

I have completed all of the quests in Occultism except for one; the single quest tied to an advancement.  1.18.2 seems to have different advancements than 1.16 (E6).

```/say @a[advancements={minecraft:story/mine_diamond=true}]```

I see [playername] playername when I run the above command.

```/say @a[advancements={occultism:summon_foliot_cleaner=true}]```

Doesn't exist, I have completed the ritual, I've got a book that holds the janitor, and I've even tried having them clean up items into my dump-chest.

```/say @a[advancements={occultism:occultism/summon_foliot_cleaner=true}]```

With the double prefix the test succeeds.

PS: there's also a typo "				title: "Summon Foliiot Janitor"  

Edit: copy/paste didn't include the =true part.

https://github.com/EnigmaticaModpacks/Enigmatica8/blob/14dfa044c39e46a654bbd85419b2e20823c585ed/config/ftbquests/quests/chapters/occultism.snbt

### Crash Report

_No response_

### Latest Log

_No response_

### Have you modified the modpack?

Yes

### User Modifications

N/A to this issue.

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

_No response_

### PR DESCRIPTION
**Pull request by Kanzaji**
Resolves #295

### CODE REVIEW

**Comment by NielsPilgaard** [comment]
Thaaank you!

**Comment by Darkere** [comment]
...master?

**Comment by Kanzaji** [comment]
Oh no.

**Comment by Darkere** [comment]
welp... then we are currently testing if this causes issues :D

**Comment by mjevans** [comment]
When is this getting a public release?  It's been a couple of weeks.

**Comment by Kanzaji** [comment]
This... was already released I think

**Comment by Kanzaji** [comment]
That is probably the problem that was caused because this was merged to `master` 😅 I did check latest release, and quest fix was actually implemented.

**Pull request merged**
