### PR TITLE
Porting quests from e6

### PR DESCRIPTION
**Pull request by Halfdeaf**
This is a port of 90% of quests that are available from E6. Some issues still need resolving like the thumbnails for the rewards not showing up. I deleted all irrelevant quests and chapters and hid Ars Nouveu because it needs a bit more of a rework than I going to do right now.

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Oh damn, nice work!!! Did you also go through the reward loot tables and check for mod items we don't have?

**Comment by Halfdeaf** [comment]
Yes, all the loot tables are fixed

**Comment by Halfdeaf** [comment]
I did my best to find comparable items instead

**Review by NillerMedDild — APPROVED** [review]

**Comment by NillerMedDild** [comment]
Aweseome :D

**Comment by YskarGORT** [comment]
Sorry for not knowing how to do the  things, but how can i use this? How do i craft the questbook?

**Comment by NielsPilgaard** [comment]
There's a keybinding for it, and I believe you also spawn with it, and that a recipe is available through JEI.

**Comment by YskarGORT** [comment]
I looked for it, there's neither in Enigmatica 8.

**Comment by NielsPilgaard** [comment]
Oh, FTBQuests isn't in yet ^^'

**Pull request merged**
