### PR TITLE
Change Drop rates for Sage and Hemp Seeds (#339)

### PR DESCRIPTION
**Pull request by Kanzaji**
Fixes Hemp Seed drop rate override
Bumped up the rate from 0.01 to 0.025
Lowered the rate for Sage seeds from 0.1 to 0.025

This PR Resolves:
#339

### CODE REVIEW

**Comment by NielsPilgaard** [comment]
Can you explain why/how this change fixes it? 😅

**Comment by Kanzaji** [comment]
Until now, Hemp Seeds didn't drop from grass at all 😅 And the reason was... a typo in the jsons.
But I took also opportunity and lowered the drop rate of Hexerei seeds, as they were dropping a lot more often than any other seed.

**Comment by NielsPilgaard** [comment]
Nice 👍 I still can't spot the typo :P 

Would you mind changing the predicate to the forge:shears tag?

**Comment by Kanzaji** [comment]
Original JSON:
```JSON
{
  "condition": "minecraft:match_tool",
  "predicate": {
    "item": "minecraft:shears"
    }
  }
},
```

New JSON
```JSON
{
  "condition": "minecraft:match_tool",
  "predicate": {
    "items": [
      "minecraft:shears"
     ]
   }
}
```
Well not exactly a typo, but "item": just didn't work 😅|

Also sure 👍 (Tho I'm not sure if that is necessary, as those are Modified default JSONs from both mods 😅 Gonna test it out however)

**Comment by Kanzaji** [comment]
Okay so yea, it didn't actually work 😅 I also found out that Occultism seeds were dropping while holding modded Shears.
Gonna PR the fix to Hexerei / IE and Occultism as well 😄

**Comment by Kanzaji** [comment]
PRs done 👍
https://github.com/BluSunrize/ImmersiveEngineering/pull/5544
https://github.com/JoeFoxe/Hexerei-1.19/pull/24
https://github.com/klikli-dev/occultism/pull/882

**Review by NielsPilgaard — APPROVED** [review]

**Pull request merged**
