### PR TITLE
JEI QoL change -> Increase limit of columns and rows for ingredient list and bookmarks.

### PR DESCRIPTION
**Pull request by Kanzaji**
Added default-ish jei-client.toml and changed out limits for rows and colums to fix issue with JEI ingredient list and bookmarks not filing entire space avaiable and leaving huge margings ^^"

This issue wasn't reported as well, however default values are small (16/9) and it doesn't look good.

Before:
obraz

After:
obraz

### CODE REVIEW

**Comment by Darkere** [comment]
what gui scale is this on?

**Comment by Kanzaji** [comment]
Scale 2 on 1920x1080 screen

**Comment by Darkere** [comment]
I believe 2 is default. Though I always switch to 3.

**Comment by Kanzaji** [comment]
Well most of the time I need to switch back to 2, so not sure what is actually default 😅 (Could be auto?)

**Comment by Darkere** [comment]
oh could be auto....

**Comment by NielsPilgaard** [comment]
This change would override user set configs on every update, default configs go in the defaultconfigs folder :)

**Comment by Kanzaji** [comment]
Woops 😅 Good point.

**Review by NielsPilgaard — APPROVED** [review]
Thanks! good stuff :D

**Pull request merged**
